name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-18.04

    steps:
    #- uses: docker-practice/actions-setup-docker@master
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Run vagrant up
      run: wget --quiet https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_x86_64.deb && sudo dpkg -i vagrant_2.2.18_x86_64.deb && vagrant up --provider=docker

    - name: build
      run: make varnish-modules
