name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name:
      env:
        RUBY_VERSION: 2.5
      run: |
        sudo apt-get update && sudo apt-get install -y \
        g++ gcc gpg \
        libc6-dev \
        make \
        pkg-config \
        build-essential \
        curl \
        apt-transport-https \
        ca-certificates \
        lsb-release \
        git-core \
        unzip \
        zip \
        autotools-dev \
        autoconf \
        docutils-common \
        libtool \
        "ruby${RUBY_VERSION}" \
        "ruby${RUBY_VERSION}-dev"

    - name: varnish-apt-deps
      env:
        VARNISH_APT_KEY: A9897320C397E3A60C03E8BF821AD320F71BFF3D
      run:
        export GNUPGHOME="$(mktemp -d)" &&
          sudo gpg --batch --keyserver keyserver.ubuntu.com --recv-keys $VARNISH_APT_KEY &&
          sudo bash -c "gpg --batch --export export $VARNISH_APT_KEY > /etc/apt/trusted.gpg.d/varnish.gpg" &&
          gpgconf --kill all &&
          sudo bash -c "echo deb https://packagecloud.io/varnishcache/varnish64/ubuntu/ bionic main > /etc/apt/sources.list.d/varnish.list"

        sudo apt-get update

    - name: golang-and-fpm
      env:
        GOLANG_VERSION: 1.14.2
        GOLANG_SHA256: 6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3
      run:
        export GOPATH="/go"
        export PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"
        sudo mkdir -p "$GOPATH/src" "$GOPATH/bin" && sudo chmod -R 777 "$GOPATH"

        sudo gem install fpm-cookery --no-ri --no-rdoc

    - name: build
      run: |
        for d in recipes/* ; do
          cd $d
          sudo fpm-cook install-deps
          fpm-cook package
          cd ../..
        done

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all-debs
        path: recipes/**/pkg