name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name:
      env:
        RUBY_VERSION: 2.5
        VARNISH_APT_KEY: A9897320C397E3A60C03E8BF821AD320F71BFF3D
        GOLANG_VERSION: 1.14.2
        GOLANG_SHA256: 6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3
      run: |
        apt-get update && apt-get install -y \
        g++ \
        gcc \
        libc6-dev \
        make \
        pkg-config \
        build-essential \
        curl \
        apt-transport-https \
        ca-certificates \
        lsb-release \
        git-core \
        unzip \
        zip \
        autotools-dev \
        autoconf \
        docutils-common \
        libtool \
        "ruby${RUBY_VERSION}" \
        "ruby${RUBY_VERSION}-dev"

        export GNUPGHOME="$(mktemp -d)" && \
          gpg --batch --keyserver keyserver.ubuntu.com --recv-keys $VARNISH_APT_KEY && \
          gpg --batch --export export $VARNISH_APT_KEY > /etc/apt/trusted.gpg.d/varnish.gpg && \
          gpgconf --kill all && \
          echo deb https://packagecloud.io/varnishcache/varnish64/ubuntu/ bionic main > /etc/apt/sources.list.d/varnish.list

        apt-get update
        export GOPATH="/go"
        export PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"
        mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

        gem install fpm-cookery --no-ri --no-rdoc




    - name: build
      run: fpm-cook package varnish-modules
